### ISSUE TITLE
error in iOs 9 safari : `SyntaxError: Unexpected keyword 'const'. Const declarations are not supported in strict mode.`

### ISSUE THREAD

**Issue by francoisromain** [vuejs/vuepress#1259]
- [x] I confirm that this is a issue rather than a question.

I asked about it here but had no answer, so I guess it is a bug: https://forum.vuejs.org/t/vuepress-syntaxerror-unexpected-keyword-const-const-declarations-are-not-supported-in-strict-mode/55488

#### Steps to reproduce

repo: https://github.com/annegabrielledumont/pilates.annegabrielle.com

#### What is expected?

No Error

#### What is actually happening?

There is an error in iOs 9 safari : `SyntaxError: Unexpected keyword 'const'. Const declarations are not supported in strict mode.`

#### Other relevant information

- Your OS: MacOs 10.13.6
- Node.js version: 11.9.0
- Browser version: iOs 9.3.5, Safari
- Is this a global or local install? local and global
- Which package manager did you use for the install? npm

How can I fix that ? thank you

**Comment by ulivz** [comment]
This has been fixed and please update your dep to latest version (1.0.0-alpha.37)

```  
    "@vuepress/plugin-active-header-links": "^1.0.0-alpha.0",
    "@vuepress/plugin-search": "^1.0.0-alpha.0",
```

**Comment by francoisromain** [comment]
@ulivz I removed `plugin-search` and updated `plugin-active-header-links` but there is still the same bug. you can check the repo here: https://github.com/annegabrielledumont/pilates.annegabrielle.com
