### ISSUE TITLE
Html Webpack Plugin error when theme is set up

### ISSUE THREAD

**Issue by raisty** [vuejs/vuepress#2628]
- [x] I confirm that this is an issue rather than a question.

## Bug report

Deploying and enabling the theme [ououe](https://github.com/tolking/vuepress-theme-ououe) give us result with error: `TypeError: Cannot read property '0' of undefined`. Started with `yarn dev`.

#### Steps to reproduce

Theme repo [ououe](https://github.com/tolking/vuepress-theme-ououe).

1. Install Vuepress latest version (^1.6.0)
1. Install ououe theme
1. Setup in config theme to `ououe`
1. start dev server

#### What is expected?

I am expecting the blog, but insted I am getting the error.

#### What is actually happening?

Following error on the screen:

```
Html Webpack Plugin:

  TypeError: Cannot read property '0' of undefined
  
  - index.js:14 exports.normalizeHeadTag
    [blog]/[@vuepress]/core/lib/node/util/index.js:14:22
  
  - HeadPlugin.js:23 tags.forEach.tag
    [blog]/[@vuepress]/core/lib/node/webpack/HeadPlugin.js:23:28
  
  - Array.forEach
  
  - HeadPlugin.js:22 compilation.hooks.htmlWebpackPluginAlterAssetTags.tapAsync
    [blog]/[@vuepress]/core/lib/node/webpack/HeadPlugin.js:22:21
  
  
  - new Promise
  
  
  - Hook.js:154 AsyncSeriesWaterfallHook.lazyCompileHook
    [blog]/[tapable]/lib/Hook.js:154:20
  
  - index.js:673 
    [blog]/[vuepress-html-webpack-plugin]/index.js:673:47
  
  - index.js:187 Promise.resolve.then.then.then.then.then.then.then.result
    [blog]/[vuepress-html-webpack-plugin]/index.js:187:18
  
  - task_queues.js:86 processTicksAndRejections
    internal/process/task_queues.js:86:5
```

#### Other relevant information

- Output of `npx vuepress info` in my VuePress project:

```
Environment Info:

  System:
    OS: macOS 10.15.6
  Binaries:
    Node: 11.13.0 - ~/.nvm/versions/node/v11.13.0/bin/node
    Yarn: 1.22.4 - ~/.yarn/bin/yarn
    npm: 6.14.6 - ~/.nvm/versions/node/v11.13.0/bin/npm
  Browsers:
    Firefox: 81.0
  npmPackages:
    @vuepress/core:  1.6.0 
    @vuepress/theme-default:  1.6.0 
    vuepress: ^1.6.0 => 1.6.0 
  npmGlobalPackages:
    vuepress: Not Found
```

**Comment by d-pollard** [comment]
Closing since this seems to have been resolved, see here for steps: https://github.com/tolking/vuepress-theme-ououe/issues/27#issuecomment-700753178

**Comment by raisty** [comment]
Actually this issue is still valid, resolved just for the particular theme. I believe Vuejs have still difficulties.
